local OutfitData = {
    -- Classic
    Hair = "",

    Hat = "",
    FaceAccessory = "",
    NeckAccessory = "",
    ShoulderAccessory = "",
    FrontAccessory = "",
    BackAccessory = "",
    WaistAccessory = "",

    -- Layered Clothing
    TShirtAccessory = "",
    ShirtAccessory = "",
    PantsAccessory = "",
    JacketAccessory = "",
    SweaterAccessory = "",
    ShortsAccessory = "",
    LeftShoeAccessory = "",
    RightShoeAccessory = "",
    DressSkirtAccessory = "",

    -- Face Accessories
    EyebrowAccessory = "",
    EyelashAccessory = "",
}

export type OutfitData = typeof(OutfitData)

return OutfitData