local OutfitData = {
    -- Classic
    Hair = 0,

    Hat = 0,
    FaceAccessory = 0,
    NeckAccessory = 0,
    ShoulderAccessory = 0,
    FrontAccessory = 0,
    BackAccessory = 0,
    WaistAccessory = 0,

    -- Layered Clothing
    TShirtAccessory = 0,
    ShirtAccessory = 0,
    PantsAccessory = 0,
    JacketAccessory = 0,
    SweaterAccessory = 0,
    ShortsAccessory = 0,
    LeftShoeAccessory = 0,
    RightShoeAccessory = 0,
    DressSkirtAccessory = 0,

    -- Face Accessories
    EyebrowAccessory = 0,
    EyelashAccessory = 0,
}

return OutfitData