local PlaceMannequinData = {
    Slot = 0,
    Mannequin = "",

    Outfit = {
        Shirt = "",
        Pants = "",
        TShirt = "",
        Face = "",
        Head = "",
        Hair = "",

        Hat = {},
        FaceAccessory = {},
        NeckAccessory = {},
        ShoulderAccessory = {},
        FrontAccessory = {},
        BackAccessory = {},
        WaistAccessory = {},
    }
}

return PlaceMannequinData