local PlaceMannequinData = {
	MannequinId = 0,

	Outfit = {
		Hair = {},

		Hat = {},
		FaceAccessory = {},
		NeckAccessory = {},
		ShoulderAccessory = {},
		FrontAccessory = {},
		BackAccessory = {},
		WaistAccessory = {},

		ShirtAccessory = {},
		PantsAccessory = {},
		JacketAccessory = {},
		SweaterAccessory = {},
		ShortsAccessory = {},
		LeftShoeAccessory = {},
		RightShoeAccessory = {},
		DressSkirtAccessory = {},
	}
}

return PlaceMannequinData