local PlayerData = {
    Gold = 100,

    PortalLevel = 1,
    PortalSpeed = 8,

    Gamepasses = {
        VIP = false,
        x2Speed = false,
        x3Spawn = false,
        x5Spawn = false,
        AutoBuy = false,
        AutoSpawn = false,
        x2Luck = false,
        x2MutationLuck = false,
        x4Luck = false,
        x4MutationLuck = false,
    },

    Assets = {},          -- Clothes, hats, accessories, etc.
    Inventory = {},       -- Potions, tickets, keys, consumables
    OwnedMannequins = {},
    PlacedMannequins = {},

    Platforms = {
        [1] = {
            Unlocked = true,
            PlacedMannequin = {},
            HasMannequin = false,
        },
        [2] = {
            Unlocked = true,
            PlacedMannequin = {},
            HasMannequin = false,
        },
        [3] = {
            Unlocked = true,
            PlacedMannequin = {},
            HasMannequin = false,
        },
        [4] = {
            Unlocked = true,
            PlacedMannequin = {},
            HasMannequin = false,
        },
        [5] = {
            Unlocked = true,
            PlacedMannequin = {},
            HasMannequin = false,
        },
        [6] = {
            Unlocked = true,
            PlacedMannequin = {},
            HasMannequin = false,
        },
        [7] = {
            Unlocked = false,
            PlacedMannequin = {},
            HasMannequin = false,
        },
        [8] = {
            Unlocked = false,
            PlacedMannequin = {},
            HasMannequin = false,
        },
        [9] = {
            Unlocked = false,
            PlacedMannequin = {},
            HasMannequin = false,
        },
        [10] = {
            Unlocked = false,
            PlacedMannequin = {},
            HasMannequin = false,
        },
        [11] = {
            Unlocked = false,
            PlacedMannequin = {},
            HasMannequin = false,
        },
        [12] = {
            Unlocked = false,
            PlacedMannequin = {},
            HasMannequin = false,
        },
        [13] = {
            Unlocked = false,
            PlacedMannequin = {},
            HasMannequin = false,
        },
        [14] = {
            Unlocked = false,
            PlacedMannequin = {},
            HasMannequin = false,
        },
        [15] = {
            Unlocked = false,
            PlacedMannequin = {},
            HasMannequin = false,
        },
        [16] = {
            Unlocked = false,
            PlacedMannequin = {},
            HasMannequin = false,
        },
        [17] = {
            Unlocked = false,
            PlacedMannequin = {},
            HasMannequin = false,
        },
        [18] = {
            Unlocked = false,
            PlacedMannequin = {},
            HasMannequin = false,
        },
        [19] = {
            Unlocked = false,
            PlacedMannequin = {},
            HasMannequin = false,
        },
        [20] = {
            Unlocked = false,
            PlacedMannequin = {},
            HasMannequin = false,
        },
        [21] = {
            Unlocked = false,
            PlacedMannequin = {},
            HasMannequin = false,
        },
        [22] = {
            Unlocked = false,
            PlacedMannequin = {},
            HasMannequin = false,
        },
        [23] = {
            Unlocked = false,
            PlacedMannequin = {},
            HasMannequin = false,
        },
        [24] = {
            Unlocked = false,
            PlacedMannequin = {},
            HasMannequin = false,
        },
        [25] = {
            Unlocked = false,
            PlacedMannequin = {},
            HasMannequin = false,
        },
        [26] = {
            Unlocked = false,
            PlacedMannequin = {},
            HasMannequin = false,
        },
        [27] = {
            Unlocked = false,
            PlacedMannequin = {},
            HasMannequin = false,
        },
        [28] = {
            Unlocked = false,
            PlacedMannequin = {},
            HasMannequin = false,
        },
        [29] = {
            Unlocked = false,
            PlacedMannequin = {},
            HasMannequin = false,
        },
        [30] = {
            Unlocked = false,
            PlacedMannequin = {},
            HasMannequin = false,
        },
    },

    PortalSettings = {
        AutoSpawn = false,
        AutoBuy = false,
        x2Speed = false,
        x3Spawn = false,
        AutoCommon = false,
        AutoUncommon = false,
    },

    Statistics = {
        PlayTime = 0,
    }
}

return PlayerData