local Remotes = {
    OpenSettingsUIRemote = "OpenSettingsUIRemote",
    OpenMannequinSelectorUIRemote = "OpenMannequinSelectorUIRemote",
    OpenMannequinCustomizationUIRemote = "OpenMannequinCustomizationUIRemote",    
    UpdateMannequinSelectorUIRemote = "UpdateMannequinSelectorUIRemote",
    PopupUIRemote = "PopupUIRemote",

    PlaceMannequinRemote = "PlaceMannequinRemote",

    PopupUIBindable = "PopupUIBindable",
}

return Remotes;