local Remotes = {
    OpenSettingsUIRemote = "OpenSettingsUIRemote",
    OpenMannequinSelectorUIRemote = "OpenMannequinSelectorUIRemote",
    OpenMannequinCustomizationUIRemote = "OpenMannequinCustomizationUIRemote",    
    UpdateMannequinSelectorUIRemote = "UpdateMannequinSelectorUIRemote",
    UpdateInventoryUIRemote = "UpdateInventoryUIRemote",
    PopupUIRemote = "PopupUIRemote",

    PlaceMannequinRemote = "PlaceMannequinRemote",

    GetPlayerDataRemote = "GetPlayerDataRemote",
    GetPreviewAssetsRemote = "GetPreviewAssetsRemote",

    SaveOutfitMannequinRemote = "SaveOutfitMannequinRemote",

    GetAsset3DPreviewRemote = "GetAsset3DPreviewRemote",

    PopupUIBindable = "PopupUIBindable",
}

return Remotes;