local Tags = {
	ExitButton = "ExitButton",
	BuyItemPrompt = "BuyItemPrompt",
	Mannequin = "Mannequin",
    MannequinPlatformPrompt = "MannequinPlatformPrompt",
    PlaceMannequinButton = "PlaceMannequinButton",
	Conveyor = "Conveyor",
	Plot = "Plot",
	SpawnPoint = "SpawnPoint",
    MenuButton = "MenuButton",
    OpenPortalSettings = "OpenPortalSettings",
    PortalSpawnButton= "PortalSpawnButton",
    MannequinDisplay = "MannequinDisplay",

    Common = "Common",
    Uncommon = "Uncommon",
    Rare = "Rare",
    Epic = "Epic",
    Legendary = "Legendary",

}

return Tags