local Tags = {
	ExitButton = "ExitButton",
	BuyAssetPrompt = "BuyAssetPrompt",
	Mannequin = "Mannequin",
    OpenMannequinSelectorUITag = "OpenMannequinSelectorUITag",
    OpenMannequinCustomizationUITag = "OpenMannequinCustomizationUITag",

	Conveyor = "Conveyor",
	Plot = "Plot",
	SpawnPoint = "SpawnPoint",
    MenuButton = "MenuButton",
    OpenPortalSettings = "OpenPortalSettings",
    PortalSpawnButton= "PortalSpawnButton",
    MannequinDisplay = "MannequinDisplay",

    SlotsUITag = "SlotsUITag",

    Common = "Common",
    Uncommon = "Uncommon",
    Rare = "Rare",
    Epic = "Epic",
    Legendary = "Legendary",

}

return Tags