local AssetsDatabase = {
	["130708845795870"] = {
		Name = "Woof Hoodie Monochrome",
		AssetId = 130708845795870,
		AccessoryType = Enum.AccessoryType.Jacket,
		Price = 100,
		Income = 10,	
		Camera = {
			Distance = 4.5,
			Height = 0,
			Rotation = Vector3.new(0, 180, 0),
			PreviewRotation = Vector3.new(0, 180, 0),
		}
	},
	["17896926875"] = {
		Name = "Black Winged Hoodie Jacket",
		AssetId = 17896926875,
		AccessoryType = Enum.AccessoryType.Jacket,
		Price = 100,
		Income = 10,
		Camera = {
			Distance = 3.0,
			Height = 0,
			Rotation = Vector3.new(0, 180, 0),
			PreviewRotation = Vector3.new(0, 180, 0),
		}
	},
	["119633773761227"] = {
		Name = "Gothic Black Messy Hair w Cross",
		AssetId = 119633773761227,
		AccessoryType = Enum.AccessoryType.Hair,
		Price = 100,
		Income = 10,
		Creator = "smellyFartUGC",
		Camera = {
			Distance = 3.0,
			Height = 0,
			Rotation = Vector3.new(0, 180, 0),
			PreviewRotation = Vector3.new(0, 180, 0),
		}
	},
	["135853370706445"] = {
		Name = "Black/White Bear Slippers",
		AssetId = 135853370706445,
		AccessoryType = "Shoes",
		Price = 100,
		Income = 10,
		Creator = "Snoopsie UGC",
		IsBundle = true,
		Camera = {
			Distance = 3.0,
			Height = 0,
			Rotation = Vector3.new(0, 180, 0),
			PreviewRotation = Vector3.new(0, 180, 0),
		}
	}
}

return AssetsDatabase