local AssetsDatabase = {
	[130708845795870] = {
		Name = "Woof Hoodie Monochrome",
		AssetId = 130708845795870,
		AccessoryType = "Jacket",
		Price = 100,
		Income = 10,	
		Camera = {
			Distance = 4.5,
			Height = 0,
			Rotation = Vector3.new(0, 180, 0),
			PreviewRotation = Vector3.new(0, 180, 0),
		}
	},
	[17896926875] = {
		Name = "Black Winged Hoodie Jacket",
		AssetId = 17896926875,
		AccessoryType = "Jacket",
		Price = 100,
		Income = 10,
		Camera = {
			Distance = 3.0,
			Height = 0,
			Rotation = Vector3.new(0, 180, 0),
			PreviewRotation = Vector3.new(0, 180, 0),
		}
	}
}

return AssetsDatabase