local PortalUpgradeDatabase = {
	[1] = {
		UpgradeCost = 12_500,
	},

	[2] = {
		UpgradeCost = 185_000,
	},

	[3] = {
		UpgradeCost = 3_750_000,
	},

	[4] = {
		UpgradeCost = 68_000_000,
	},

	[5] = {
		UpgradeCost = 1_950_000_000,
	},

	[6] = {
		UpgradeCost = 84_000_000_000,
	},

	[7] = {
		UpgradeCost = 6_750_000_000_000,
	},

	[8] = {
		UpgradeCost = 935_000_000_000_000,
	},

	[9] = {
		UpgradeCost = 248_000_000_000_000_000,
	},

	[10] = {
		UpgradeCost = 18_500_000_000_000_000_000,
	},
}

return PortalUpgradeDatabase