local PortalLevelDatabase = {
	[1] = {
		Low = 45,
		Average = 30,
		Good = 15,
		Excellent = 6,
		Superior = 2.5,
		Masterwork = 1,
		Perfect = 0.4,
		Pristine = 0.1,
	},

	[2] = {
		Low = 38,
		Average = 32,
		Good = 18,
		Excellent = 7,
		Superior = 3,
		Masterwork = 1.3,
		Perfect = 0.5,
		Pristine = 0.2,
	},

	[3] = {
		Low = 32,
		Average = 30,
		Good = 22,
		Excellent = 9,
		Superior = 4,
		Masterwork = 2,
		Perfect = 0.7,
		Pristine = 0.3,
	},

	[4] = {
		Low = 25,
		Average = 28,
		Good = 25,
		Excellent = 12,
		Superior = 5,
		Masterwork = 3,
		Perfect = 1.5,
		Pristine = 0.5,
	},

	[5] = {
		Low = 20,
		Average = 25,
		Good = 28,
		Excellent = 15,
		Superior = 6,
		Masterwork = 4,
		Perfect = 1.5,
		Pristine = 0.5,
	},

	[6] = {
		Low = 15,
		Average = 22,
		Good = 30,
		Excellent = 18,
		Superior = 8,
		Masterwork = 5,
		Perfect = 1.5,
		Pristine = 0.5,
	},

	[7] = {
		Low = 10,
		Average = 18,
		Good = 30,
		Excellent = 22,
		Superior = 10,
		Masterwork = 7,
		Perfect = 2,
		Pristine = 1,
	},

	[8] = {
		Low = 7,
		Average = 15,
		Good = 28,
		Excellent = 25,
		Superior = 12,
		Masterwork = 8,
		Perfect = 3,
		Pristine = 2,
	},

	[9] = {
		Low = 5,
		Average = 10,
		Good = 25,
		Excellent = 28,
		Superior = 15,
		Masterwork = 10,
		Perfect = 4,
		Pristine = 3,
	},

	[10] = {
		Low = 2,
		Average = 8,
		Good = 20,
		Excellent = 30,
		Superior = 18,
		Masterwork = 12,
		Perfect = 6,
		Pristine = 4,
	},
}

return PortalLevelDatabase